<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Demande extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Educazad_model');
    }

    /*
     * Listing of tb_am_users
     */
    function index()
    {
        $data['all_demandes'] = $this->Educazad_model->get_multiple('tb_im_demandes', array(), 'tb_im_demandes.demande_id','DESC');

        $data['_view'] = 'demandes/index';
        $this->load->view('layouts/main',$data);
    }
    public function detailProduit($productID){
        //all products
        $products = $this->Educazad_model->get_multiple('tb_im_produits',
            array('intrant_id'=>$productID), 'tb_im_produits.intrant_id','DESC');
        $product = array(
            'price' => $products['prix_unitaire'],
            'libelle' => $products['libelle'], 
        );
        return $product;
    }
    /*
     * Adding a new tb_am_user
     */
    function add()
    {
        //all products
        $data['all_intrants'] = $this->Educazad_model->get_multiple('tb_im_produits', array(), 'tb_im_produits.intrant_id','DESC');

        //all shops
         $data['all_shops'] = $this->Educazad_model->get_multiple('tb_im_shops', array(), 'tb_im_shops.shop_id','DESC');

        $this->load->library('form_validation');

        $this->form_validation->set_rules('intrant_sid','Intrant SID','required');
        $this->form_validation->set_rules('qte_demandee','qte_demandee','required');
        $this->form_validation->set_rules('benef_nom','benef_nom','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');

            $code_intrant = strstr($this->input->post('intrant_sid'), '-', true);
            $intrant_sid = (!empty($code_intrant)) ? $code_intrant : $this->input->post('intrant_sid');
            //new quqntity
            $new_sortie_qte=$this->input->post('qte_demandee');


            //get shop id
             $code_shop = strstr($this->input->post('shop_sid'), '-', true);
            $shop_sid = (!empty($code_shop)) ? $code_shop : $this->input->post('shop_sid');

            $prix_db = $this->Educazad_model->get_unique('tb_im_produits', array('intrant_id'=>$intrant_sid))->prix_unitaire;

            $prix_total=$prix_db*$new_sortie_qte;
            $montant_tva= $prix_total*16/100;
            $montant_total_encaisse=$montant_tva+$prix_total;

                //get all data in array
            $params = array(
                'benef_nom' => $this->input->post('benef_nom'),
                'qte_demandee' => $new_sortie_qte,
                'date_demandee' => $current_datetime,
                'date_ajout' =>  $current_datetime,
                'produit_sid' => $intrant_sid,
                'shop_sid'=>$shop_sid,
                'prix_vente_produit'=>$prix_db, 
                'prix_total'=>$prix_total,
                'montant_tva'=>$montant_tva,
                'montant_total_encaisse'=>$montant_total_encaisse,

            );
           
            //recuperation de la quantite stock
            $existing_quantity_produit = $this->Educazad_model->get_unique('tb_im_produits', array('intrant_id'=>$intrant_sid))->qte_stock;

            //verifier si la quantite commandee est superieur a la quantite stock du produit
            if ($new_sortie_qte > $existing_quantity_produit){
                $data['error_sortie'] = "Vous avez saisie une quantité très élevée par rapport à la quantité de stock.
                 Le stock actuel du produit selectionné est de $existing_quantity_produit. ";
                $data['_view'] = 'demandes/add';
                $this->load->view('layouts/main',$data);
            }else {

                $new_qte_stock = $existing_quantity_carburant - $new_sortie_qte;    //new quantity stock
                $param_intrant = array('qte_stock' => $new_qte_stock);          //array carburants
             
                $this->Educazad_model->update_data('tb_im_produits',$param_intrant, array('intrant_id'=>$intrant_sid));
                $this->Educazad_model->insert_data('tb_im_demandes',$params);
                redirect('demande/index');
            
            }
        }
        else
        {
            $data['_view'] = 'demandes/add';
            $this->load->view('layouts/main',$data);
        }
    }
}