<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Entree extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Educazad_model');
    }

    /*
     * Listing of tb_am_users
     */
    function index()
    {
        $data['all_entrees'] = $this->Educazad_model->get_multiple('tb_im_entrees', array(), 'tb_im_entrees.entree_id','DESC');

        $data['_view'] = 'entrees/index';
        $this->load->view('layouts/main',$data);
    } /*
     * Listing of tb_am_users
     */
    function listingFournisseurs()
    {
        $data['all_fss'] = $this->Educazad_model->get_multiple('tb_im_fournisseurs', array(), 'tb_im_fournisseurs.fss_id','DESC');

        $data['_view'] = 'entrees/listingFournisseurs';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_am_user
     */
    function add()
    {
        $data['all_intrants'] = $this->Educazad_model->get_multiple('tb_im_produits', array(), 'tb_im_produits.intrant_id','DESC');
        $data['all_fss'] = $this->Educazad_model->get_multiple('tb_im_fournisseurs', array(), 'tb_im_fournisseurs.fss_id','DESC');

        $this->load->library('form_validation');

        $this->form_validation->set_rules('intrant_sid','Intrant SID','required');
        $this->form_validation->set_rules('date_entree','date_entree','required');
        $this->form_validation->set_rules('qte_entree','qte_entree','required');
        $this->form_validation->set_rules('fss_sid','fss_sid','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');

            $code_intrant = strstr($this->input->post('intrant_sid'), '-', true);
            $intrant_sid = (!empty($code_intrant)) ? $code_intrant : $this->input->post('intrant_sid');

            //fournisseur
              $code_fss = strstr($this->input->post('fss_sid'), '-', true);
            $fss_sid = (!empty($code_fss)) ? $code_fss : $this->input->post('fss_sid');
            //new quqntity
            $new_entry_qte=$this->input->post('qte_entree');

            $frais_transport=$this->input->post('frais_transport');

            //prix unitaire
            $prix_achat_produit = $this->input->post('prix_achat_produit');

            $prix_total=$prix_achat_produit*$new_sortie_qte;
            $montant_tva= $prix_total*16/100;
            $montant_total_depense=$montant_tva+$prix_total;

            $params = array(
                'fss_sid' => $fss_sid,
                'produit_sid' => $intrant_sid,
                'qte_entree' => $new_entry_qte,
                'date_entree' => $this->input->post('date_entree'),
                'date_ajout' =>  $current_datetime,
                'prix_achat_produit'=>$prix_achat_produit, 
                'prix_total'=>$prix_total,
                'montant_tva'=>$montant_tva,
                'montant_total_depense'=>$montant_total_depense,
                'frais_transport'=>$frais_transport,

                
            );
            $existing_quantity_stock = $this->Educazad_model->get_unique('tb_im_produits', array('intrant_id'=>$intrant_sid))->qte_stock;
            $new_qte_stock=$existing_quantity_stock+$new_entry_qte;
            $param_intrant = array('qte_stock' => $new_qte_stock);

            $this->Educazad_model->insert_data('tb_im_entrees',$params);
            $this->Educazad_model->update_data('tb_im_produits',$param_intrant, array('intrant_id'=>$intrant_sid));
            redirect('entree/index');
        }
        else
        {
            $data['_view'] = 'entrees/add';
            $this->load->view('layouts/main',$data);
        }
    }
     function addFournisseur()
    {
        
        $this->load->library('form_validation');
        $this->form_validation->set_rules('fss_nom','fss_nom','required');
        $this->form_validation->set_rules('fss_adresse','fss_adresse','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');

            $params = array(
                'nom' => $this->input->post('fss_nom').'-'.$this->input->post('fss_postnom').'-'.$this->input->post('fss_prenom'),
                'contact' => $this->input->post('fss_phone'),
                'adresse' => $this->input->post('fss_adresse'),
                 'type_fss' => $this->input->post('fss_type'),
                'date_created' =>  $current_datetime,
            
            );
            
            $this->Educazad_model->insert_data('tb_im_fournisseurs',$params);
            redirect('entree/listingFournisseurs');
        }
        else
        {
            $data['_view'] = 'entrees/addFournisseur';
            $this->load->view('layouts/main',$data);
        }
    }
}