<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ordonance extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ordonance_model');
    } 

    /*
     * Listing of ordonances
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('ordonance/index?');
        $config['total_rows'] = $this->Ordonance_model->get_all_ordonances_count();
        $this->pagination->initialize($config);

        $data['ordonances'] = $this->Ordonance_model->get_all_ordonances($params);
        
        $data['_view'] = 'ordonance/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new ordonance
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'malade_noms' => $this->input->post('malade_noms'),
                'malade_age' => $this->input->post('malade_age'),
                
                'malade_telephone' => $this->input->post('malade_telephone'),
                'ordonance_numero' => $this->input->post('ordonance_numero'),
                'ordonance_date' => $this->input->post('ordonance_date'),
                'nom_medecin' => $this->input->post('nom_medecin'),
                'spec_medecin' => $this->input->post('spec_medecin'),
                'ordonance_details' => $this->input->post('ordonance_details'),

            );
            
            $ordonance_id = $this->Ordonance_model->add_ordonance($params);
            redirect('ordonance/index');
        }
        else
        {
            
            $data['_view'] = 'ordonance/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a ordonance
     */
    function edit($ordon_id)
    {   
        // check if the ordonance exists before trying to edit it
        $data['ordonance'] = $this->Ordonance_model->get_ordonance($ordon_id);
        
        if(isset($data['ordonance']['ordon_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'malade_noms' => $this->input->post('malade_noms'),
                    'malade_age' => $this->input->post('malade_age'),
                   
                    'malade_telephone' => $this->input->post('malade_telephone'),
					'ordonance_numero' => $this->input->post('ordonance_numero'),
					'ordonance_date' => $this->input->post('ordonance_date'),
					'nom_medecin' => $this->input->post('nom_medecin'),
                    'spec_medecin' => $this->input->post('spec_medecin'),
					'ordonance_details' => $this->input->post('ordonance_details'),
                );

                $this->Ordonance_model->update_ordonance($ordon_id,$params);            
                redirect('ordonance/index');
            }
            else
            {

                $data['_view'] = 'ordonance/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The ordonance you are trying to edit does not exist.');
    } 

    /*
     * Deleting ordonance
     */
    function remove($ordon_id)
    {
        $ordonance = $this->Ordonance_model->get_ordonance($ordon_id);

        // check if the ordonance exists before trying to delete it
        if(isset($ordonance['ordon_id']))
        {
            $this->Ordonance_model->delete_ordonance($ordon_id);
            redirect('ordonance/index');
        }
        else
            show_error('The ordonance you are trying to delete does not exist.');
    }
    
}
