<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class ShopVente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Educazad_model');
    }

    /*
     * Listing of tb_am_users
     */
    function index()
    {
        $data['all_shops'] = $this->Educazad_model->get_multiple('tb_im_shops', array(), 'tb_im_shops.shop_id','DESC');

        $data['_view'] = 'shops/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_am_user
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('libelle','Libelle','required');
        $this->form_validation->set_rules('shop_adresse','Prix prix_unitaire','required');
        //$this->form_validation->set_rules('shop_observation','shop_observation','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');
            
            $params = array(
                'shop_nom' => $this->input->post('libelle'),
                'shop_adresse' => $this->input->post('shop_adresse'),
                'date_ajout' => $current_datetime,
                
            );
            $this->Educazad_model->insert_data('tb_im_shops',$params);
            redirect('ShopVente/index');
        }
        else
        {
            $data['_view'] = 'shops/add';
            $this->load->view('layouts/main',$data);
        }
    }

    function stockJournal()
    {
        $data['all_stocks'] = $this->Educazad_model->shop_produit();
        //all products
        $data['all_intrants'] = $this->Educazad_model->get_multiple('tb_im_produits', array(), 'tb_im_produits.intrant_id','DESC');

        //all shops
         $data['all_shops'] = $this->Educazad_model->get_multiple('tb_im_shops', array(), 'tb_im_shops.shop_id','DESC');

        $data['_view'] = 'stock/index';
        $this->load->view('layouts/main',$data);
    }

    function addStockShop(){
         $data['all_intrants'] = $this->Educazad_model->get_multiple('tb_im_produits', array(), 'tb_im_produits.intrant_id','DESC');

        //all shops
         $data['all_shops'] = $this->Educazad_model->get_multiple('tb_im_shops', array(), 'tb_im_shops.shop_id','DESC');

         $this->load->library('form_validation');

        $this->form_validation->set_rules('intrant_sid','intrant_sid','required');
        $this->form_validation->set_rules('qte_stock_initiale','qte_stock_initiale','required');
        $this->form_validation->set_rules('shop_sid','shop_sid','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');


            $code_intrant = strstr($this->input->post('intrant_sid'), '-', true);
            $intrant_sid = (!empty($code_intrant)) ? $code_intrant : $this->input->post('intrant_sid');
            //new quqntity
            $qte_stock_init=$this->input->post('qte_stock_initiale');

            //get shop id
             $code_shop = strstr($this->input->post('shop_sid'), '-', true);
            $shop_sid = (!empty($code_shop)) ? $code_shop : $this->input->post('shop_sid');

            //tableau de donnees
            $params = array(
                'produit_sid' => $intrant_sid,
                'stock_init' => $qte_stock_init,
                'date_created' => $current_datetime,
                'shop_sid'=>$shop_sid,
                'qte_tot_vendue'=>0
            );
             //recuperation de la quantite stock du carburant
            $existing_quantity_produit = $this->Educazad_model->get_unique('tb_im_produits', array('intrant_id'=>$intrant_sid))->qte_stock;

            //verifier si la quantite commandee est superieur a la quantite stock du produit
            if ($qte_stock_init > $existing_quantity_produit){
                $data['error_sortie'] = "Vous avez saisie une quantité initiale très élevée de ce point de venteb 
                par rapport à la quantité de stock du produit selectionné.
                 Le stock actuel du produit selectionné est de $existing_quantity_produit. ";
                $data['_view'] = 'stock/add';
                $this->load->view('layouts/main',$data);
            }else {

                $new_qte_stock_carburant = $existing_quantity_produit - $qte_stock_init;    //new quantity stock carburant
                $param_intrant = array('qte_stock' => $new_qte_stock_carburant);          //array carburants
                
                //update stock
                $this->Educazad_model->update_data('tb_im_produits',$param_intrant, array('intrant_id'=>$intrant_sid));
                $this->Educazad_model->insert_data('tb_im_stockshops',$params);
                redirect('ShopVente/stockJournal');

            }
        }
        else
        {
            $data['_view'] = 'stock/add';
            $this->load->view('layouts/main',$data);
        }
    }
}