<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Prescription_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get prescription by prescrip_id
     */
    function get_prescription($prescrip_id)
    {
        return $this->db->get_where('tb_cons_prescriptions',array('prescrip_id'=>$prescrip_id))->row_array();
    }
    
    /*
     * Get all prescriptions count
     */
    function get_all_prescriptions_count()
    {
        $this->db->from('tb_cons_prescriptions');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all prescriptions
     */
    function get_all_prescriptions($params = array())
    {
        $this->db->order_by('prescrip_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_cons_prescriptions')->result_array();
    }
        
    /*
     * function to add new prescription
     */
    function add_prescription($params)
    {
        $this->db->insert('tb_cons_prescriptions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update prescription
     */
    function update_prescription($prescrip_id,$params)
    {
        $this->db->where('prescrip_id',$prescrip_id);
        return $this->db->update('tb_cons_prescriptions',$params);
    }
    
    /*
     * function to delete prescription
     */
    function delete_prescription($prescrip_id)
    {
        return $this->db->delete('tb_cons_prescriptions',array('prescrip_id'=>$prescrip_id));
    }
}
