<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Produit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_cons_medicament by product_id
     */
    function get_tb_cons_medicament($product_id)
    {
        return $this->db->get_where('tb_im_produits',array('intrant_id'=>$product_id))->row_array();
    }
        
    /*
     * Get all tb_cons_medicaments
     */
    function get_all_medicaments()
    {
        $this->db->order_by('intrant_id', 'desc');
        return $this->db->get('tb_im_produits')->result_array();
    }
        
    /*
     * function to add new tb_cons_medicament
     */
    function add_tb_cons_medicament($params)
    {
        $this->db->insert('tb_im_produits',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_cons_medicament
     */
    function update_tb_cons_medicament($product_id,$params)
    {
        $this->db->where('intrant_id',$product_id);
        return $this->db->update('tb_im_produits',$params);
    }
    
    /*
     * function to delete tb_cons_medicament
     */
    function delete_tb_cons_medicament($product_id)
    {
        return $this->db->delete('tb_im_produits',array('intrant_id'=>$product_id));
    }
}
